# Application Name
spring.application.name=Query-Executor

# ==========================
# Database Configuration
# ==========================
spring.datasource.url=${DB_URL}


spring.datasource.username=${DB_USER}



spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# ==========================
# JPA / Hibernate Settings (optional but common)
# ==========================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==========================
# Server Configuration (optional)
# ==========================
server.port=${PORT}